spring.application.name=apigatewayapp
server.port=9000
spring.main.web-application-type=servlet
spring.main.allow-bean-definition-overriding=true
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:free
spring.datasource.username=system
spring.datasource.password=Oracle@2026
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.routes[0].id=firstservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://FIRSTSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/first/**

spring.cloud.gateway.server.webflux.routes[1].id=secondservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://SECONDSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/second/**


