create table categories(
category_id           INT 
                      generated always as identity
                      (start with 100 increment by 1), 
                      --primary key, --column level
                      
category_name varchar2(100) not null,
primary key (category_id) --table level
)

CREATE TABLE products (
    product_id          NUMBER GENERATED by default AS IDENTITY 
                        (START WITH 1 INCREMENT BY 1) 
                        PRIMARY KEY,
                        
    product_name         VARCHAR2(100) NOT NULL,
    
    product_price        NUMBER(10,2) NOT NULL default(0),
    
    product_code         VARCHAR2(50) NOT NULL UNIQUE,
    
    description          VARCHAR2(1000),
    
    release_date         DATE,

    image                BLOB,

    rating               NUMBER(2,1),
    
    category_id          int  --references categories (category_id) <--> column level constraint,
    --foreign key (category_id) references categories (category_id) <--> table level constraint
);

alter table products
add foreign key (category_id) references categories(category_id);
