# Microprofile server properties
server.port=9001
server.host=0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics.rest-request.enabled=false

# Application properties. This is the default greeting
app.greeting=Hello


# Datasource properties
javax.sql.DataSource.FreeDataSource.dataSourceClassName=oracle.jdbc.pool.OracleDataSource
javax.sql.DataSource.FreeDataSource.dataSource.url=jdbc:oracle:thin:@localhost:1521:free
javax.sql.DataSource.FreeDataSource.dataSource.user=system
javax.sql.DataSource.FreeDataSource.dataSource.password=Oracle@2026
